### ISSUE TITLE
Getting DS is not defined

### ISSUE THREAD

**Issue by brandonjmckay** [ember-cli/ember-cli-shims#26]
I'm getting this error from `ember-cli-shims/app-shims.js`:

```
Uncaught ReferenceError: DS is not defined
    at eval (eval at evaluate (unknown source), <anonymous>:1:1)
    at Object.InjectedScript._evaluateOn (<anonymous>:895:55)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluateOnCallFrame (<anonymous>:954:21)
    at http://localhost:4200/agent/assets/vendor.js:67613:3
    at mod.state (http://localhost:4200/agent/assets/vendor.js:150:29)
    at tryFinally (http://localhost:4200/agent/assets/vendor.js:30:14)
    at requireModule (http://localhost:4200/agent/assets/vendor.js:148:5)
    at requireFrom (http://localhost:4200/agent/assets/vendor.js:121:12)
    at reify (http://localhost:4200/agent/assets/vendor.js:106:22)
```

I'm on Ember 1.13.2, and Ember Data 1.13.4, and Ember CLI 0.2.7.

**Comment by stefanpenner** [comment]
i believe this is fixed on the #canary branch:  https://github.com/ember-cli/ember-cli-shims/tree/canary

Can you try?

**Comment by brandonjmckay** [comment]
Absolutely! Thanks.

**Comment by brandonjmckay** [comment]
Ya, I think that did it. Thanks very much! You are lightning!

**Comment by brandonjmckay** [comment]
![giphy](https://cloud.githubusercontent.com/assets/1518678/8504198/ed7b1aa2-2181-11e5-9ad4-8d490ff87115.gif)

**Comment by stefanpenner** [comment]
@tomdale is #canary ready for mainline?

**Comment by rwjblue** [comment]
@stefanpenner - Yes, I believe that it is ready.

**Comment by stefanpenner** [comment]
its still only in canary

**Comment by tomdale** [comment]
Merged

**Comment by brandonjmckay** [comment]
So is this in a release now? Or should I just point to master for now?

**Comment by tomdale** [comment]
@brandonjmckay We have not done a release yet. We probably need to reach consensus in https://github.com/emberjs/rfcs/pull/68 before doing an initial release. `master` should be good for now.

**Comment by brandonjmckay** [comment]
Many thanks!
