### ISSUE TITLE
Ember Build failing with 1.x versions

### ISSUE THREAD

**Issue by bluscreen** [ember-cli/ember-cli-shims#96]
Hello.. unfortunately my build is failing with the 1.0.2 version.  Ember 2.9.1

```
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat 'Y:\xyz\tmp\source_map_concat-input_base_path-QEfGWDfe.tmp\0\bower_components\ember-cli-shims\app-shims.js'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at FSMonitor._measure (Y:\xyz\node_modules\heimdalljs-fs-monitor\index.js:66:21)
    at Object.statSync (Y:\xyz\node_modules\heimdalljs-fs-monitor\index.js:82:30)
    at Concat.keyForFile (Y:\xyz\node_modules\broccoli-caching-writer\index.js:87:20)
    at Array.map (native)
    at Concat.CachingWriter._conditionalBuild (Y:\xyz\node_modules\broccoli-caching-writer\index.js:109:65)
    at Y:\xyz\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\read_compat.js:61:34
    at tryCatch (Y:\xyz\node_modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (Y:\xyz\node_modules\rsvp\dist\rsvp.js:553:13)

The broccoli plugin was instantiated at: 
    at Concat.Plugin (Y:\xyz\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at Concat.CachingWriter [as constructor] (Y:\xyz\node_modules\broccoli-caching-writer\index.js:18:10)
    at new Concat (Y:\xyz\node_modules\broccoli-concat\concat.js:32:17)
    at module.exports (Y:\xyz\node_modules\broccoli-concat\index.js:26:10)
    at EmberApp.concatFiles (Y:\xyz\node_modules\ember-cli\lib\broccoli\ember-app.js:370:10)
    at EmberApp._concatFiles (Y:\xyz\node_modules\ember-cli\lib\broccoli\ember-app.js:383:15)
    at EmberApp.javascript (Y:\xyz\node_modules\ember-cli\lib\broccoli\ember-app.js:1269:12)
    at EmberApp.toArray (Y:\xyz\node_modules\ember-cli\lib\broccoli\ember-app.js:1640:10)
    at EmberApp.toTree (Y:\xyz\node_modules\ember-cli\lib\broccoli\ember-app.js:1662:30)
    at module.exports (Y:\xyz\ember-cli-build.js:41:16)

Build failed.
```

does anyone have an idea about this?
cheers
Daniel

**Comment by rwjblue** [comment]
1.x of this repo is an addon (npm package) that is to be used with ember-source@2.11.0 or higher, and not intended to be used from bower at all.

**Comment by bluscreen** [comment]
dear @rwjblue thanks for informing me about this. i just found this old dependency in bower.json
```
    "ember": "2.9.1",
    "ember-cli-shims": "0.1.3",
```
so you say i should entirely remove the shims from bower? how should i install them instead?
best regards
daniel

**Comment by bluscreen** [comment]
thx
